name: my_clean_app
description: "A new Flutter project with Clean Architecture and BLoC."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # State Management
  flutter_bloc: ^8.1.3
  # Value Equality
  equatable: ^2.0.5
  # Dependency Injection
  get_it: ^7.6.0
  # Functional Programming (for Either type)
  dartz: ^0.10.1
  # Networking
  dio: ^5.4.3
  # JSON Serialization
  json_annotation: ^4.9.0
  # Local Storage
  shared_preferences: ^2.3.0
  # Network Connectivity
  connectivity_plus: ^5.0.1
  # Custom Fonts
  google_fonts: ^6.2.0
  # Routing
  go_router: ^14.1.0
  # Logging
  logger: ^2.3.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  # Code Generation
  build_runner: ^2.4.9
  json_serializable: ^6.7.1

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
